<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TO96F33" failures="0" tests="14" name="tests.CartTests" time="2.292" errors="2" timestamp="2025-10-07T23:02:22 IST" skipped="12">
  <testcase classname="tests.CartTests" name="verifyItemPresenceInCart" time="2.160">
    <skipped/>
  </testcase> <!-- verifyItemPresenceInCart -->
  <testcase classname="tests.CartTests" name="verifyIncreasingItemQuantity" time="0.000">
    <skipped/>
  </testcase> <!-- verifyIncreasingItemQuantity -->
  <testcase classname="tests.CartTests" name="verifyInitialEmptyCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyInitialEmptyCart -->
  <testcase classname="tests.CartTests" name="verifyItemPresenceInCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyItemPresenceInCart -->
  <testcase classname="tests.CartTests" name="verifyTotalCartPriceWithMultipleItems" time="0.000">
    <skipped/>
  </testcase> <!-- verifyTotalCartPriceWithMultipleItems -->
  <testcase classname="tests.CartTests" name="verifyItemPresenceInCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyItemPresenceInCart -->
  <testcase classname="tests.CartTests" name="verifyItemPresenceInCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyItemPresenceInCart -->
  <testcase classname="tests.CartTests" name="verifyItemPresenceInCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyItemPresenceInCart -->
  <testcase classname="tests.CartTests" name="verifyCheckoutButtonNavigatesToCheckoutPage" time="0.029">
    <error message="Item not found: Cafe Latte" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Item not found: Cafe Latte
at pages.MenuPage.addItemToCart(MenuPage.java:39)
at tests.CartTests.verifyCheckoutButtonNavigatesToCheckoutPage(CartTests.java:145)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- verifyCheckoutButtonNavigatesToCheckoutPage -->
  <testcase classname="tests.CartTests" name="verifyMultipleItemsArePresent" time="0.000">
    <skipped/>
  </testcase> <!-- verifyMultipleItemsArePresent -->
  <testcase classname="tests.CartTests" name="verifyDecreasingItemQuantity" time="0.000">
    <skipped/>
  </testcase> <!-- verifyDecreasingItemQuantity -->
  <testcase classname="tests.CartTests" name="verifyItemIsRemovedWhenQuantityIsZero" time="0.000">
    <skipped/>
  </testcase> <!-- verifyItemIsRemovedWhenQuantityIsZero -->
  <testcase classname="tests.CartTests" name="verifySingleItemTotalPrice" time="0.000">
    <skipped/>
  </testcase> <!-- verifySingleItemTotalPrice -->
  <testcase classname="tests.CartTests" name="tearDown" time="0.103">
    <error message="Timed out waiting for driver server to stop.
Build info: version: &#039;4.35.0&#039;, revision: &#039;1c58e5028b&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.8&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [88b964b261f6360f9663cc4fb2f66e79, quit {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 140.0.7339.210, chrome: {chromedriverVersion: 140.0.7339.207 (17230b545fd..., userDataDir: C:\Users\SEHARK~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:59816}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59816/devtoo..., se:cdpVersion: 140.0.7339.210, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 88b964b261f6360f9663cc4fb2f66e79" type="org.openqa.selenium.WebDriverException">
      <![CDATA[org.openqa.selenium.WebDriverException: Timed out waiting for driver server to stop.
Build info: version: '4.35.0', revision: '1c58e5028b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [88b964b261f6360f9663cc4fb2f66e79, quit {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 140.0.7339.210, chrome: {chromedriverVersion: 140.0.7339.207 (17230b545fd..., userDataDir: C:\Users\SEHARK~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:59816}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59816/devtoo..., se:cdpVersion: 140.0.7339.210, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 88b964b261f6360f9663cc4fb2f66e79
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:557)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:630)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:634)
at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:458)
at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:404)
at managers.DriverManager.quitDriver(DriverManager.java:68)
at tests.CartTests.tearDown(CartTests.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:805)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4ce1a4ad[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@ddcae96[Wrapped task = org.openqa.selenium.remote.http.jdk.JdkHttpClient$$Lambda/0x0000025b011c08c0@9e33bf5]] rejected from java.util.concurrent.ThreadPoolExecutor@11f0a5a1[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 55]
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:160)
... 32 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4ce1a4ad[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@ddcae96[Wrapped task = org.openqa.selenium.remote.http.jdk.JdkHttpClient$$Lambda/0x0000025b011c08c0@9e33bf5]] rejected from java.util.concurrent.ThreadPoolExecutor@11f0a5a1[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 55]
at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.executeAsync(JdkHttpClient.java:384)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:413)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:212)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.lambda$execute$1(DriverCommandExecutor.java:126)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
... 3 more
]]>
    </error>
  </testcase> <!-- tearDown -->
</testsuite> <!-- tests.CartTests -->
